name: padelio-app
services:
  payment-service:
    container_name: payment-service
    platform: linux/amd64
    # image: masadamsahid/padelio-payment-service:1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - .env